title:            Swapnil Abnave
description:      "'Knowledge is Devine'"
logo:             assets/images/saraswati.svg
disqus_shortname: swapnilabnave
share:            true
# layout: null

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
#url:        	  http://swapnilabnave.github.io

# Analytics and webmaster tools stuff goes here
google_analytics: UA-64088251-1

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
# markdown:    kramdown
#paginate:    5
#paginate_path: "page:num"
#plugins: [jekyll-paginate]
# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title

theme: jekyll-theme-minimal
show_downloads: false